// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "196f1b58-9b13-42e3-b6ff-fe38f9172931";

const char SSID[]               = "Infinix HOT 40i";    // Network SSID (name)
const char PASS[]               = "sefah2223";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "sF7jiU1!fSfRw6#L870KWGg!X";    // Secret device password

void onPhChange();
void onTDSChange();
void onWPTemperaureChange();

float ph;
float tDS;
float wPTemperaure;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(ph, READWRITE, ON_CHANGE, onPhChange);
  ArduinoCloud.addProperty(tDS, READWRITE, ON_CHANGE, onTDSChange);
  ArduinoCloud.addProperty(wPTemperaure, READWRITE, ON_CHANGE, onWPTemperaureChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
